# Generated by Django 4.1.5 on 2023-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_saving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
