# Generated by Django 4.1.5 on 2023-01-10 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0001_initial"),
        ("users", "0005_alter_user_saving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="saving",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="savings.saving",
            ),
        ),
    ]
