# Generated by Django 4.1.5 on 2023-01-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_saving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
