# Generated by Django 4.1.5 on 2023-01-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_saving"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="saving",
        ),
    ]
