# Generated by Django 4.1.5 on 2023-01-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_cards", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="credit_card",
            name="name",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
    ]
