# Generated by Django 4.1.5 on 2023-01-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credit_cards", "0002_remove_credit_card_transactions"),
        ("credit_cards", "0003_credit_card_name"),
    ]

    operations = []
