# Generated by Django 4.1.5 on 2023-01-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credit_cards", "0004_merge_20230109_1311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="credit_card",
            name="closing_day",
            field=models.PositiveIntegerField(),
        ),
    ]
