# Generated by Django 4.1.5 on 2023-01-11 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("savings", "0003_alter_saving_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saving",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saving",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
