# Generated by Django 4.1.5 on 2023-01-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("savings", "0004_alter_saving_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saving",
            name="user",
        ),
    ]
