# Generated by Django 4.1.5 on 2023-01-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseEntrie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction",
                    models.CharField(
                        choices=[("EXPENSE", "Expense"), ("ENTRIE", "Entrie")],
                        max_length=15,
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        choices=[("MONEY", "Money"), ("CREDIT CARD", "Credit Card")],
                        default="MONEY",
                        max_length=15,
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("expiration", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                ("is_paid", models.BooleanField(default=False)),
            ],
        ),
    ]
