# Generated by Django 4.1.5 on 2023-01-05 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseEntrie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction",
                    models.CharField(
                        choices=[("EXPENSE", "Expense"), ("ENTRIE", "Entrie")],
                        max_length=15,
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        choices=[("MONEY", "Money"), ("CREDIT CARD", "Credit Card")],
                        default="MONEY",
                        max_length=15,
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("expiration", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_entrie",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
