# Generated by Django 4.1.5 on 2023-01-06 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("expenses_entries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseentrie",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_entrie",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
