# Generated by Django 4.1.5 on 2023-01-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_id"),
        ("expenses_entries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseentrie",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="categories.category",
            ),
            preserve_default=False,
        ),
    ]
