# Generated by Django 4.1.5 on 2023-01-06 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expenses_entries", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseentrie",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_entrie",
                to="expenses_entries.expenseentrie",
            ),
        ),
    ]
