# Generated by Django 4.1.5 on 2023-01-06 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_remove_category_expense_entrie"),
        ("expenses_entries", "0003_expenseentrie_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenseentrie",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_entrie",
                to="categories.category",
            ),
        ),
    ]
