# Generated by Django 4.1.5 on 2023-01-06 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("expenses_entries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="expense_entrie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="expenses_entries.expenseentrie",
            ),
        ),
    ]
