# Generated by Django 4.1.5 on 2023-01-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="expense_entrie",
        ),
    ]
